# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4622e254eaaecef477ee6a048b1507c7e2729b705870e7488040c32a84d1b62c64f0c9217cdf3e02284548dc61bb8e9e9fd3e83494fd2dea5c2b6b959ec63972

test:
  secret_key_base: cf667ad5e91cc66b17f27fa669c05d873aa2ecc62eceb6a3174bead3f9d75614ceb572f31428ca20e9dcd7b61c2d78eefced9baf8976802f8db922ca10f8bb56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
